### ISSUE TITLE
No Barcode Action

### ISSUE THREAD

**Issue by OliverTempel** [pluginsGLPI/barcode#20]
I have installed Barcode version 2.1.0 and GLPI 9.2.2.
I have no Barcode Action in Computer List or elsewhere.
Checked Access Rights for Super-Admin and check Config.

**Comment by dreamsness** [comment]
Within our company, we had the same problem with GLPI 0.90.5 with the barcode plugin 0.90+1.0. Now I have migrated GLPI to version 9.3.0 with barcode 2.2.0, and we have the same problem.
The QRCode generation works, but concerning the barcode generation it doesn't work....
When I generate the barcode, the.pdf created is blank, I have a blank page. 
For information, I have tried all types of barcodes. And I didn't touch the default configuration of the plugin.

Thank you for you help
Best regards,
Josemd

**Comment by victoria1984** [comment]
Good morning,
I am working with version 9.3 of GLPI and the last of this plugin and I have the same problem. the qr code is generated correctly, but the rest of the codes are not generated, or it shows a blank page or returns an error or NO ASSET TAG. (attached image).

How can I generate the bar codes?
It is important for me since I work only with bar dofigos, not with qr.

Thank you very much for the help

Greetings.
![image](https://user-images.githubusercontent.com/38318643/46138877-63f3ea00-c24d-11e8-8022-9696408a3121.png)

**Comment by dreamsness** [comment]
It seems that the barcode is generated in relation to an inventory number.
After trying to manually enter an inventory number on a device (a computer for example), the barcode is generated correctly!
In addition, how can we update the "inventory number" field of our equipment, automatically via Fusion Inventory?
Give me a feedback please.
Thank you

**Comment by cedric-anne** [comment]
Hi,

> It seems that the barcode is generated in relation to an inventory number.
> After trying to manually enter an inventory number on a device (a computer for example), the barcode is generated correctly!

Yes, the barcode is generated using the "inventory number" field. If this field is blank, then no barcode can be generated.

> In addition, how can we update the "inventory number" field of our equipment, automatically via Fusion Inventory?

I do not know well Fusion Inventory. You should ask for this on dedicated forum https://forum.glpi-project.org/viewforum.php?id=20 .

Regards
