### ISSUE TITLE
Barcode with GLPI 10.0

### ISSUE THREAD

**Issue by EstevanCastro1** [pluginsGLPI/barcode#97]
Barcode does not work in the latest version of GLPI, please could you fix this as the company depends on these QR codes.

**Comment by blackxthink** [comment]
> Barcode does not work in the latest version of GLPI, please could you fix this as the company depends on these QR codes.

I know it might not be a perfect solution, but the software nicelabel (not free) might help you.
It can connect to your database directly and print using label printers (Dymo, Brother, etc.).

That's the way we are going since the plugin was a pain in the butt trying to print only one sticker with dymo printers.
